A
hilti: uncaught exception, myException2 with argument 'hallo' (from /home/robin/work/hilti/tests/.tmp/hilti.exceptions.throw-3/throw.hlt:14-15)
