RUN 1
hilti: uncaught exception, DivisionByZero (from /home/robin/work/hilti/tests/.tmp/hilti.threads.exceptions/exceptions.hlt:36-37)
RUN 2
hilti: uncaught exception, DivisionByZero (from /home/robin/work/hilti/tests/.tmp/hilti.threads.exceptions/exceptions.hlt:36-37)
RUN 3
hilti: uncaught exception, DivisionByZero (from /home/robin/work/hilti/tests/.tmp/hilti.threads.exceptions/exceptions.hlt:36-37)
RUN 4
hilti: uncaught exception, DivisionByZero (from /home/robin/work/hilti/tests/.tmp/hilti.threads.exceptions/exceptions.hlt:36-37)
RUN 5
hilti: uncaught exception, DivisionByZero (from /home/robin/work/hilti/tests/.tmp/hilti.threads.exceptions/exceptions.hlt:36-37)
