module Main

import Hilti

type myException = exception
void run()
{

  local ref<myException> e
  local ref<myException> e_2
  
  
      # pred: { <none> } succ: { [0058] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0057] call Hilti::print ("A")
      # pred: { [0057] } succ: { [0059] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0058] exception.__begin_handler @__catch_1 myException
      # pred: { [0058] } succ: { [0060], [0064] }
      # def: { run%e.2 } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { run%e.2 }
      # now-dead: { <none> }
      [0059] e = new myException
      # pred: { [0059] } succ: { [0061], [0064] }
      # def: { <none> } clear: { <none> } mod: { run%e.2 } read: { <none> }
      # live-in: { run%e.2 } live-out: { <none> }
      # now-dead: { run%e.2 }
      [0060] exception.throw e
      # pred: { [0060] } succ: { [0062], [0064] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0061] call Hilti::print ("Cannot be reached")
      # pred: { [0061] } succ: { [0063], [0064] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0062] exception.__end_handler
      # pred: { [0062] } succ: { [0068] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0063] jump @__catch_cont_1
  
  @__catch_1:
      # pred: { [0059], [0060], [0061], [0062] } succ: { [0065] }
      # def: { run%e_2.2 } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { run%e.2, run%e_2.2 }
      [0064] e_2 = exception.__get_and_clear
      # pred: { [0064] } succ: { [0066] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0065] call Hilti::print ("Caught it!")
      # pred: { [0065] } succ: { [0068] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0066] jump @__catch_cont_1
  
  @__catch_cont_1:
      # pred: { [0063], [0066] } succ: { [0069] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0068] call Hilti::print ("C")
      # pred: { [0068] } succ: { <none> }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0069] return.void
  
}



  # pred: { <none> } succ: { <none> }
  # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
  # live-in: { <none> } live-out: { <none> }
  # now-dead: { <none> }
  [0071] block.end

