Caught it!
<Main::myException>
init
