
>>> e = new myException "hello"
wrong-new.hlt:10-10: error, exception does not take an argument [pass::hilti::Validator]
wrong-new.hlt: Aborting due to verification error.
error running hiltic, aborting
